# Generated by Django 4.2.6 on 2023-11-28 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_stations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.TextField()),
                ('route', models.TextField()),
                ('service_level', models.TextField()),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WagonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trains')),
                ('wagon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wagontype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wagon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wagontype')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trains')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='route_trains',
            field=models.ManyToManyField(related_name='routes', to='app.trains'),
        ),
    ]
