# Generated by Django 4.2.6 on 2023-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
