# Generated by Django 4.2.6 on 2023-12-25 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_wagon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
    ]
