# Generated by Django 4.2.6 on 2023-12-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_trains_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='route',
            field=models.TextField(),
        ),
    ]
