# Generated by Django 4.2.6 on 2023-12-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_trains_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_trains',
        ),
    ]
