# Generated by Django 4.2.6 on 2023-12-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_route_route_trains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trains',
            name='seats',
        ),
    ]
