# Generated by Django 4.2.6 on 2023-12-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_trains_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='route',
        ),
    ]
