# Generated by Django 4.2.6 on 2023-12-25 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_remove_schedule_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trains')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wagon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wagon')),
            ],
        ),
    ]
