# Generated by Django 4.2.6 on 2023-12-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='questions',
            new_name='question',
        ),
    ]
